// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrgElGY0wSFhAUIiJoZdn7mgBAS-TVLe4',
    appId: '1:520922891777:web:236ce97d91e74f74dc2200',
    messagingSenderId: '520922891777',
    projectId: 'prove-2298b',
    authDomain: 'prove-2298b.firebaseapp.com',
    storageBucket: 'prove-2298b.firebasestorage.app',
    measurementId: 'G-D0N8ZWJJHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALY-FTtLPDaKrqO2VdBzXtwO1EbKuCUBE',
    appId: '1:520922891777:android:1bb33caa225d26eddc2200',
    messagingSenderId: '520922891777',
    projectId: 'prove-2298b',
    storageBucket: 'prove-2298b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnn8NKEzFntqF3qdwNURkDzmltbc_NcIk',
    appId: '1:520922891777:ios:82c6ffc430c8fdc0dc2200',
    messagingSenderId: '520922891777',
    projectId: 'prove-2298b',
    storageBucket: 'prove-2298b.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnn8NKEzFntqF3qdwNURkDzmltbc_NcIk',
    appId: '1:520922891777:ios:82c6ffc430c8fdc0dc2200',
    messagingSenderId: '520922891777',
    projectId: 'prove-2298b',
    storageBucket: 'prove-2298b.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrgElGY0wSFhAUIiJoZdn7mgBAS-TVLe4',
    appId: '1:520922891777:web:fd23f02b3e081fdbdc2200',
    messagingSenderId: '520922891777',
    projectId: 'prove-2298b',
    authDomain: 'prove-2298b.firebaseapp.com',
    storageBucket: 'prove-2298b.firebasestorage.app',
    measurementId: 'G-FHFBC6PKLH',
  );

}